### PR TITLE
Move events to separate files

### PR DESCRIPTION
**Pull request by samwilson**
Create new layouts for 'events' and 'event' and use them for an events list and individual events' pages.

Fix up a couple of errors of dates in older files.

### CODE REVIEW

**Comment by samwilson** [comment]
There's more to be done to make the layouts work, but this PR is just focusing on the events data. I know adding a second root template is probably not great, but I didn't want to make the changes to `Default.html` too big.

**Comment by BudgieInWA** [comment]
From a quick read through, the structure looks good to me. What is the directive that ties the files in the year directories into the "events" variable?

**Comment by samwilson** [comment]
> From a quick read through, the structure looks good to me. What is the directive that ties the files in the year directories into the "events" variable?

They all have `layout: event`, which is a bit of an overloading of a different attribute, but it seemed silly to introduce a `type: event` or similar (or "if it has a date, it's an event") so I went with that. There are some weird gotchas about querying page lists in Jekyll (e.g. you can't really do "where attribute x doesn't exist").

Then the actual querying is done with filters, for the homepage:

```liquid
{% assign events_data = site.pages | where: "layout", "event" | where: "homepage", "true" %}
```

and for the events list:

```liquid
{% assign events_data = site.pages | where: "layout", "event" | sort: "path" %}
```

`path` is a default attribute of pages, along with things like `url` and `published`, which we shouldn't re-define as far as I can tell; not that it stops us from doing so! That's why I had to change our `url` to `registration_url`.

**Comment by BudgieInWA** [comment]
Ah, makes sense. They are all just pages as far as Jekyll is concerned. Great!

**Pull request merged**
